# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfjournal < Formula
  desc "Record Terraform runs with git context, timing, and resource events"
  homepage "https://github.com/Owloops/tfjournal"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Owloops/tfjournal/releases/download/v0.1.0/tfjournal_Darwin_x86_64"
      sha256 "4995e8a82916451aee0a23818ba4ad09ca2a9c55b0f6553cf2818370468cc448"

      def install
        bin.install "tfjournal_Darwin_x86_64" => "tfjournal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Owloops/tfjournal/releases/download/v0.1.0/tfjournal_Darwin_arm64"
      sha256 "5b86b76313da4889fb0f33b187323b262f59b1084c0e02547867763b7046f413"

      def install
        bin.install "tfjournal_Darwin_arm64" => "tfjournal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Owloops/tfjournal/releases/download/v0.1.0/tfjournal_Linux_x86_64"
      sha256 "a113add31d24a44e4eca8d8b2b2ac4d3c5a4d6837af595c14075233306e4c415"
      def install
        bin.install "tfjournal_Linux_x86_64" => "tfjournal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Owloops/tfjournal/releases/download/v0.1.0/tfjournal_Linux_arm64"
      sha256 "9b97b02b8d9c651eb98032aee95ab565fb195ab725a96962ee18acfb12b9a3e7"
      def install
        bin.install "tfjournal_Linux_arm64" => "tfjournal"
      end
    end
  end
end
