# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfjournal < Formula
  desc "Record Terraform runs with git context, timing, and resource events"
  homepage "https://github.com/Owloops/tfjournal"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Owloops/tfjournal/releases/download/v0.1.1/tfjournal_Darwin_x86_64"
      sha256 "f912f8689f945cbbf0048b784e8eb43eb7bcdc2c8534dba397ac79317a0d8bbe"

      def install
        bin.install "tfjournal_Darwin_x86_64" => "tfjournal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Owloops/tfjournal/releases/download/v0.1.1/tfjournal_Darwin_arm64"
      sha256 "4f40439ed91b89b37ffaee953709101f9f561bfe84b02de24b6c23ab7091d93a"

      def install
        bin.install "tfjournal_Darwin_arm64" => "tfjournal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Owloops/tfjournal/releases/download/v0.1.1/tfjournal_Linux_x86_64"
      sha256 "e4d93a96996920fc79b68a592768e3dea49595eb8ab9941703be380b803eb20f"
      def install
        bin.install "tfjournal_Linux_x86_64" => "tfjournal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Owloops/tfjournal/releases/download/v0.1.1/tfjournal_Linux_arm64"
      sha256 "072b6eeddd7718fbdddfb3a7c969f213a4cde76d90ea8fea6123b14d5f62dece"
      def install
        bin.install "tfjournal_Linux_arm64" => "tfjournal"
      end
    end
  end
end
